% Fig2.m
% written by Matt Osman (mattosman@arizona.edu / mo549@cam.ac.uk), Apr 2023

% this file generates Figure 2 of Koffman et al. (in revision at Nature Geoscience)
% highlighting divergences in publishing and coauthor inclusivity across women- vs. man led studies

% DEPENDENCIES
% 1. Fig1_mc.mat **
% ** generated by running Fig1.m

clear
homeFold = cd; 
cd ../; workFold = cd;
addpath(genpath('Dependencies/')); 
% check on dependency availability
if ~isfile("Dependencies/Data/Fig1_mc.mat")
    error('Missing file "Fig1_mc.mat". Please run Fig1.m first')
end

%% User-defined input parameters

mc = 1000; % number of monte carlo gender simulations (suggested mc >= 1000)
timeBins = [1969, 2011; 
            2012, 2021]; % input the time bins over which to compare -- make sure the size(timeBins,1) = 2 or 3

%% Load the abstract data

if isfile("abstracts.mat")
    load('abstracts.mat')
else
    error('Missing file "abstracts.mat". Please first run saveAbstracts.m')
end

%% Estimate initialed author genders

if isfile("persons.mat")
    load('persons.mat')
else
    error('Missing file "persons.mat". Please first run savePersons.m')
end
genderP = cell(size(simpleNames)); 
probability = cell(size(simpleNames)); 
h = waitbar(0, 'Matching initialed authors ... please wait...');
for i = 1:size(simpleNames,1)
    if ~isempty(simpleNames{i})
    genderP{i} = cell(size(simpleNames{i})); 
    probability{i} = cell(size(simpleNames{i})); 
    for j = 1:size(simpleNames{i},1)
        if ~isempty(simpleNames{i}{j})
        genderP{i}{j} = strings(size(simpleNames{i}{j})); 
        probability{i}{j} = nan(size(simpleNames{i}{j})); 
        for k = 1:size(simpleNames{i}{j},1)
            if ~strcmp(gender{i}{j}(k),"") % if gender information already exists in 'gender', then use that info!
                genderP{i}{j}(k) = gender{i}{j}(k); 
                probability{i}{j}(k) = prob{i}{j}(k); 
            else % otherwise, try to use prior coauthorship overlap to see if we can infer it
                I = strcmp(simpleNames{i}{j}(k),persons.persons);
                In = 1:size(simpleNames{i}{j},1); In = find(In~=k);
                if ~isempty(In)
                    if sum(I) > 0 % if there's a name match...
                        % find if there exists at least 1 coauthor overlap
                        if ~isempty(intersect(persons.coauthors{I},simpleNames{i}{j}(In)))
                            genderP{i}{j}(k) = persons.gender(I);
                            probability{i}{j}(k) = persons.probability(I);
                        end
                    end
                end
            end
        end
        end
    end
    end
    waitbar(i / size(simpleNames,1))
end
close(h)
gender = genderP; clearvars genderP
prob = probability; clearvars probability

%% Determine metrics by each study where first author gender is denoted

study.type = [];
study.year = [];
study.nations = [];
study.coauthors = [];
study.cite = [];
study.genderR = []; % gender ratio
study.genderN = []; % number of females 
study.genderF = []; % gender of first author

for i = 1:length(years)
    for j = 1:length(gender{i})
        if ~isempty(gender{i}{j})
            if (gender{i}{j}(1) == "") == 0
                % country
                ca = unique(country.country{i}{j}); 
                if length(ca) == 1 % if the coauthor countries are the same as the first author' country.. 
                    study.type = [study.type; "domestic"]; 
                elseif length(ca) > 1
                    study.type = [study.type; "international"]; 
                else
                    study.type = [study.type; ""]; 
                end
                % year
                study.year = [study.year; years(i)];
                % cite rate 
                study.cite = [study.cite; log(citations{i}(j) ./ timeElapsed{i}(j))];
                % number of nationalities
                if isempty(ca) % if the coauthor countries are the same as the first author country.. 
                    study.nations = [study.nations; 0]; 
                else
                    study.nations = [study.nations; length(ca)]; 
                end            
                % number of coauthors
                study.coauthors = [study.coauthors; length(country.country{i}{j}(2:end))]; 
                % gender ratio
                if sum(~strcmp(gender{i}{j},"")) >= 2 && sum(~strcmp(gender{i}{j},""))/length(gender{i}{j}) >= 1.0 % at least more than one gender listed and at least half genders reported
                    study.genderR = [study.genderR; sum(strcmp(gender{i}{j}(2:end),"female")) ./...
                        (sum(strcmp(gender{i}{j}(2:end),"female")) + sum(strcmp(gender{i}{j}(2:end),"male")))]; 
                else
                    study.genderR = [study.genderR; NaN]; 
                end
                % number of females
                study.genderN = [study.genderN; sum(strcmp(gender{i}{j}(2:end),"female"))]; 
                % gender of first author
                study.genderF = [study.genderF; gender{i}{j}(1)]; 
            end
        end
    end
end

% preallocate
male.type = cell(size(timeBins,1),1); 
male.nations = cell(size(timeBins,1),1); 
male.coauthors = cell(size(timeBins,1),1); 
male.cite = cell(size(timeBins,1),1); 
male.genderR = cell(size(timeBins,1),1); 
male.genderN = cell(size(timeBins,1),1); 
female = male; % copy preallocated cells
% partition by man vs. woman led
for i = 1:size(timeBins,1)
    Im = study.year >= timeBins(i,1) & study.year <= timeBins(i,2) & strcmp(study.genderF,"male");
    If = study.year >= timeBins(i,1) & study.year <= timeBins(i,2) & strcmp(study.genderF,"female");
    male.type{i} = study.type(Im); female.type{i} = study.type(If); 
    male.nations{i} = study.nations(Im); female.nations{i} = study.nations(If); 
    male.cite{i} = study.cite(Im); female.cite{i} = study.cite(If); 
        I = isinf(male.cite{i}) | isnan(male.cite{i}); male.cite{i}(I) = []; % remove nan or inf val's
        I = isinf(female.cite{i}) | isnan(female.cite{i}); female.cite{i}(I) = []; % remove nan or inf val's
    male.coauthors{i} = study.coauthors(Im); female.coauthors{i} = study.coauthors(If); 
    male.genderR{i} = study.genderR(Im); female.genderR{i} = study.genderR(If); 
    male.genderN{i} = study.genderN(Im); female.genderN{i} = study.genderN(If); 
end

%%  plot impact factor

% define impact factor
name = ["Annals of Glaciology"
        "Atmospheric Chemistry & Physics"
        "Atmospheric Environment"
        "Climate Dynamics"
        "Climate of the Past"
        "Earth and Planetary Science Letters"
        "Environmental Science and Technology"
        "Geochimica et Cosmochimica Acta"
        "Geophysical Research Letters"
        "Global and Planetary Change"
        "Global Biogeochemical Cycles"
        "Journal of Geophysical Research"
        "Journal of Glaciology"
        "Nature"
        "Nature Geoscience"
        "Paleoceanography"
        "Proceedings of the National Academy of Science"
        "Quaternary Science Reviews"
        "Science"
        "Tellus Series B Chemical and Physical Meteorology B"];
IF =   [2.863
        7.197
        4.798
        4.901
        4.498
        5.785
        11.357
        5.921
        5.58
        5.114
        5.96
        4.261
        4.278
        69.5
        21.53
        3.99
        12.78
        4.571
        63.71
        2.279];

% Determine metrics for each journal
refJour = erase(string(name)," "); 
refJour = erase(refJour,"&"); 

for r = 1:length(refJour)
    jour.(refJour(r)).type = [];
    jour.(refJour(r)).year = [];
    jour.(refJour(r)).nations = [];
    jour.(refJour(r)).coauthors = [];
    jour.(refJour(r)).cite = [];
    jour.(refJour(r)).oa = [];
    jour.(refJour(r)).genderR = []; % gender ratio
    jour.(refJour(r)).genderN = []; % number of females 
    jour.(refJour(r)).genderF = []; % gender of first author
    jour.(refJour(r)).prob = []; % probability
end

h = waitbar(0,'Assigning journal metrics ... please wait');
for r = 1:length(name)
    jour.(refJour(r)).IF = IF(r);
    for i = 1:length(years)
        for j = 1:length(journals{i})
            if strcmp(journals{i}{j},name(r))
                ca = unique(country.country{i}{j}); 
                if length(ca) == 1 % if the coauthor countries are the same as the first author' country.. 
                    jour.(refJour(r)).type = [jour.(refJour(r)).type; "domestic"]; 
                elseif length(ca) > 1
                    jour.(refJour(r)).type = [jour.(refJour(r)).type; "international"]; 
                else
                    jour.(refJour(r)).type = [jour.(refJour(r)).type; ""]; 
                end
                % year
                jour.(refJour(r)).year = [jour.(refJour(r)).year; years(i)];
                % open access
                jour.(refJour(r)).oa = [jour.(refJour(r)).oa; openaccess{i}(j)];
                % cite rate 
                jour.(refJour(r)).cite = [jour.(refJour(r)).cite; (citations{i}(j) ./ timeElapsed{i}(j))];
                % number of nationalies
                if isempty(ca) % if the coauthor countries are the same as the first author' country.. 
                    jour.(refJour(r)).nations = [jour.(refJour(r)).nations; 0]; 
                else
                    jour.(refJour(r)).nations = [jour.(refJour(r)).nations; length(ca)]; 
                end            
                % number of coauthors
                jour.(refJour(r)).coauthors = [jour.(refJour(r)).coauthors; length(country.country{i}{j})]; 
                % gender
                if ~isempty(gender{i}{j})
                    % gender ratio
                    jour.(refJour(r)).genderR = [jour.(refJour(r)).genderR; sum(strcmp(gender{i}{j},"female")) ./...
                        (sum(strcmp(gender{i}{j},"female")) + sum(strcmp(gender{i}{j},"male")))]; 
                    % number of females
                    jour.(refJour(r)).genderN = [jour.(refJour(r)).genderN; sum(strcmp(gender{i}{j},"female"))]; 
                    % gender of first author
                    jour.(refJour(r)).genderF = [jour.(refJour(r)).genderF; gender{i}{j}(1)]; 
                    % probability
                    jour.(refJour(r)).prob = [jour.(refJour(r)).prob; prob{i}{j}(1)]; 
                else
                    jour.(refJour(r)).genderR = [jour.(refJour(r)).genderR; NaN]; 
                    jour.(refJour(r)).genderN = [jour.(refJour(r)).genderN; NaN]; 
                    jour.(refJour(r)).genderF = [jour.(refJour(r)).genderF; ""];                 
                    jour.(refJour(r)).prob = [jour.(refJour(r)).prob; NaN];                 
                end
            end
        end
    end
    waitbar(r / length(refJour))
end
close(h);

% Calculate uncertainty
maleFemale = ["male","female"];
h = waitbar(0,'conducting MC experiments ... please wait');
for g = 1:length(refJour)
    jour.(refJour(g)).genderMC = strings(size(jour.(refJour(g)).genderF,1),mc); % gender first author
    for k = 1:mc
        for i = 1:size(jour.(refJour(g)).genderMC,1)
                % first author
                genderFirst = jour.(refJour(g)).genderF(i);
                if ~strcmp(genderFirst,"")
                    r = rand;
                if r > jour.(refJour(g)).prob(i); genderFirst = maleFemale(~strcmp(genderFirst,maleFemale)); end
            end
            jour.(refJour(g)).genderMC(i,k) = genderFirst; 
        end
    end
    waitbar(g / length(refJour))
end
close(h)

% Define two sets of journals
[~,I] = sort(IF,'descend'); 
refPrest = refJour(I(1:4));
refOther = refJour(I(5:end)); 

% need to concatenate into 'prestige' and 'other'
prestige.type = [];
prestige.year = [];
prestige.nations = [];
prestige.coauthors = [];
prestige.cite = [];
prestige.oa = [];
prestige.genderR = []; % gender ratio
prestige.genderN = []; % number of females 
prestige.genderF = []; % gender of first author
prestige.prob = []; % probability
prestige.jour = []; % probability
prestige.genderMC = []; 
other = prestige;
for r = 1:length(refPrest)
    prestige.type = [prestige.type; jour.(refPrest(r)).type];
    prestige.year = [prestige.year; jour.(refPrest(r)).year];
    prestige.nations = [prestige.nations; jour.(refPrest(r)).nations];
    prestige.coauthors = [prestige.coauthors; jour.(refPrest(r)).coauthors];
    prestige.cite = [prestige.cite; jour.(refPrest(r)).cite];
    prestige.oa = [prestige.oa; jour.(refPrest(r)).oa];
    prestige.genderR = [prestige.genderR; jour.(refPrest(r)).genderR]; % gender ratio
    prestige.genderN = [prestige.genderN; jour.(refPrest(r)).genderN]; % number of females 
    prestige.genderF = [prestige.genderF; jour.(refPrest(r)).genderF]; % gender of first author
    prestige.prob = [prestige.prob; jour.(refPrest(r)).prob]; % probability
    prestige.jour = [prestige.jour; repmat(refPrest(r),[numel(jour.(refPrest(r)).year),1])]; % journals
    prestige.genderMC = [prestige.genderMC; jour.(refPrest(r)).genderMC]; 
end
for r = 1:length(refOther)
    other.type = [other.type; jour.(refOther(r)).type];
    other.year = [other.year; jour.(refOther(r)).year];
    other.nations = [other.nations; jour.(refOther(r)).nations];
    other.coauthors = [other.coauthors; jour.(refOther(r)).coauthors];
    other.cite = [other.cite; jour.(refOther(r)).cite];
    other.oa = [other.oa; jour.(refOther(r)).oa];
    other.genderR = [other.genderR; jour.(refOther(r)).genderR]; % gender ratio
    other.genderN = [other.genderN; jour.(refOther(r)).genderN]; % number of females 
    other.genderF = [other.genderF; jour.(refOther(r)).genderF]; % gender of first author
    other.prob = [other.prob; jour.(refOther(r)).prob]; % probability
    other.jour = [other.jour; repmat(refOther(r),[numel(jour.(refOther(r)).year),1])]; % journals
    other.genderMC = [other.genderMC; jour.(refOther(r)).genderMC]; 
end

% determine genderBalances
for i = 1:size(timeBins,1)
    % prestige
    I = prestige.year >= min(timeBins(i,:)) & prestige.year <= max(timeBins(i,:));
    Ic = [prestige.year >= min(timeBins(i,:)) & prestige.year <= max(timeBins(i,:))] & strcmp(prestige.genderF,'female');
    currError = nansum(strcmp(prestige.genderMC(I,:),'female')) ./ ...
               (nansum(strcmp(prestige.genderMC(I,:),'female'),1) + nansum(strcmp(prestige.genderMC(I,:),'male'),1));
    propFemale = nansum(strcmp(prestige.genderF(I),'female')) ./ ...
                (nansum(strcmp(prestige.genderF(I),'female')) + nansum(strcmp(prestige.genderF(I),'male')));
    femPrestige(i,:) = [propFemale,nanmean(currError),prctile(currError,2.5),prctile(currError,25),prctile(currError,50),prctile(currError,75),prctile(currError,97.5),nanstd(currError)]; 
    citePrestige(i,:) = ([nanmean(prestige.cite(Ic)),prctile(prestige.cite(Ic),2.5),prctile(prestige.cite(Ic),25),prctile(prestige.cite(Ic),50),prctile(prestige.cite(Ic),75),prctile(prestige.cite(Ic),97.5),nanstd(prestige.cite(Ic))]); 
    
    % other
    I = other.year >= min(timeBins(i,:)) & other.year <= max(timeBins(i,:));
    Ic = [other.year >= min(timeBins(i,:)) & other.year <= max(timeBins(i,:))] & strcmp(other.genderF,'female');
    currError = nansum(strcmp(other.genderMC(I,:),'female'),1) ./ ...
               (nansum(strcmp(other.genderMC(I,:),'female'),1) + nansum(strcmp(other.genderMC(I,:),'male'),1));
    propFemale = nansum(strcmp(other.genderF(I),'female')) ./ ...
                (nansum(strcmp(other.genderF(I),'female')) + nansum(strcmp(other.genderF(I),'male')));
    femOther(i,:) = [propFemale,nanmean(currError),prctile(currError,2.5),prctile(currError,25),prctile(currError,50),prctile(currError,75),prctile(currError,97.5),nanstd(currError)]; 
    citeOther(i,:) = ([nanmean(other.cite(Ic)),prctile(other.cite(Ic),2.5),prctile(other.cite(Ic),25),prctile(other.cite(Ic),50),prctile(other.cite(Ic),75),prctile(other.cite(Ic),97.5),nanstd(other.cite(Ic))]); 
end


%% Plot

cd(workFold)

% define figure parameters
fig1 = figure; hold on;
    if size(timeBins,1) == 3
    set(fig1,'units','centimeters','position',[2.5,0.5,13,20]);
    elseif size(timeBins,1) == 2
    set(fig1,'units','centimeters','position',[2.5,0.5,10.5,20]);
    end
    ax = gca; ax.Visible = 'off';
    set(fig1,'PaperPositionMode','auto');         
    set(fig1,'PaperOrientation','landscape');

% assign colors
cd Figures/cbrewer/
warning('off','all')  
    CT1 = cbrewer('seq','YlOrBr' ,9); CT1(end,:) = []; CT1(end,:) = []; CT1(end,:) = []; CT1(1,:) = []; % CT2(2,:) = CT2(1,:); 
    CT2 = cbrewer('seq','Reds' ,5);
    CT3 = cbrewer('seq','Purples' ,5);    
    CT4 = cbrewer('seq','Greys' ,5);  
    CT5 = cbrewer('seq','Blues' ,5);  
    gold = [0.975, 0.65, 0.125]; 
warning('on','all')
cd ../../

% get community representation data
load('Fig1_mc.mat');  
for i = 1:size(timeBins,1)
    I = years >= min(timeBins(i,:)) & years <= max(timeBins(i,:)) & ~isnan(nanmean(grA,2));
    propsA(i,1) = nansum(numStudies(I) .* nanmean(grA(I,:),2)) ./ sum(numStudies(I));
    propsA_std(i,1) = std(nanmean(grA(I,:),2), numStudies(I)); 
end

K = size(timeBins,1); 
adj = 0.025; 
barWidth = 0.40; 
widthVal = 0.20; 
box1Alpha = 0.50; 

ax0 = axes('position',[0.15 0.25 0.675 0.25]); hold on; grid off; 
    set(ax0,'Color','none','linewidth',1.0,'fontsize',10,'Box','on','xtick',[],'ytick',[]); hold on;
    plotVals = nanmean([ [1:(K-1)]',[2:(K)]'],2); 
    ylim([0 1]); 	
    xlim([0+0.5 K+1-0.5]);
    for i = 1:size(timeBins,1)-1
        plot([plotVals(i),plotVals(i)],[0 1],'--','linewidth',0.5,'color',CT4(end-1,:)); 
    end

% Proportion collaborators women
    ax1 = axes('position',[0.15 0.25 0.675 0.155]); hold on; grid off; 
        set(ax1,'Color','none','linewidth',1.0,'fontsize',10,'Box','off','xaxislocation','bottom'); hold on;
        set(ax1,'Xtick',[1:K],'Xticklabel',join(string(timeBins),'-'),'XTickLabelRotation',0);
        ylabel([{'Proportion women'},{'coauthors per study'}]); 
        xlabel(ax1,[{'Year range'}]); 
        ylim([0 0.5]); set(ax1,'Ytick',[0:0.2:1]); 
        xlim([0+0.5 K+1-0.5]);

    % \pm1 sigma community
    plotRange = [ax0.XLim(1), nanmean([ [1:(K-1)]',[2:(K)]'],2)', ax0.XLim(2)]'; 
    for i = 1:size(plotRange,1)-1
        b0 = fill(ax1,[plotRange(i),plotRange(i),plotRange(i+1),plotRange(i+1)], ...
            [propsA(i)-propsA_std(i),propsA(i)+propsA_std(i),propsA(i)+propsA_std(i),propsA(i)-propsA_std(i)], CT4(end-2,:),'linewidth',1); 
            b0.EdgeColor = 'none'; b0.FaceAlpha = 0.25;        
    end

    for i = 1:size(timeBins,1)
        % men
        xLoc = i-barWidth/2; cDat = male.genderR{i}; cDat(isnan(cDat)) = []; 
            % violin plot
            h = figure(101); cd Figures/Violinplot/; % procedure: run violin plot to get the plotting data:
            violins = violinplot(cDat,[0],'Width',widthVal,'Bandwidth',0.075); % ,'Bandwidth',10); % ,'Bandwidth',prctile(cDat,75) % repmat(cDat,[5,1])
            vertices = violins.ViolinPlot.Vertices; 
                upper = [vertices(1:(length(vertices)/2),1)-1, vertices(1:(length(vertices)/2),2)]; 
                lower = [vertices((length(vertices)/2+1):end,1)-1, vertices((length(vertices)/2+1):end,2)]; 
            close(h); cd ../../
            box1a = fill(ax1,[lower(:,1) + xLoc; upper(:,1) + xLoc] + adj, [lower(:,2); upper(:,2)],CT1(2,:)); 
                box1a.EdgeColor = 'k'; box1a.LineWidth = 0.5; box1a.FaceAlpha = box1Alpha; box1a.EdgeAlpha = box1Alpha + 0.2; 
            % 95 percentile range
            l = plot(ax1,[xLoc xLoc] + adj,[prctile(cDat,2.5), prctile(cDat,97.5)],'Linewidth',1,'Color',0.3.*[1 1 1]);
            % Interquartile range
            box2a = fill(ax1,[xLoc-widthVal/4, xLoc-widthVal/4, xLoc+widthVal/4, xLoc+widthVal/4] + adj,...
                [prctile(cDat,25), prctile(cDat,75), prctile(cDat,75), prctile(cDat,25)],CT1(3,:)); 
                box2a.EdgeColor = 0.3.*[1 1 1]; box2a.FaceAlpha = 1.0; 
            % mean
            l = plot(ax1,[xLoc-widthVal/4, xLoc+widthVal/4] + adj,[nanmean(cDat), nanmean(cDat)],'Linewidth',1.5,'Color',CT1(end,:));
        % women
        xLoc = i+barWidth/2; cDat = female.genderR{i}; cDat(isnan(cDat)) = []; 
            % violin plot
            h = figure(101); cd Figures/Violinplot/; % procedure: run violin plot to get the plotting data:
            violins = violinplot(cDat,[0],'Width',widthVal,'Bandwidth',0.075); % ,'Bandwidth',10); % ,'Bandwidth',prctile(cDat,75) % repmat(cDat,[5,1])
            vertices = violins.ViolinPlot.Vertices; 
                upper = [vertices(1:(length(vertices)/2),1)-1, vertices(1:(length(vertices)/2),2)]; 
                lower = [vertices((length(vertices)/2+1):end,1)-1, vertices((length(vertices)/2+1):end,2)]; 
            close(h); cd ../../
            box1b = fill(ax1,[lower(:,1) + xLoc; upper(:,1) + xLoc] - adj, [lower(:,2); upper(:,2)],CT2(2,:)); 
                box1b.EdgeColor = 'k'; box1b.LineWidth = 0.5; box1b.FaceAlpha = box1Alpha; box1b.EdgeAlpha = box1Alpha + 0.2; 
            % 95 percentile range
            l = plot(ax1,[xLoc xLoc] - adj,[prctile(cDat,2.5), prctile(cDat,97.5)],'Linewidth',1,'Color',0.3.*[1 1 1]);
            % Interquartile range
            box2b = fill(ax1,[xLoc-widthVal/4, xLoc-widthVal/4, xLoc+widthVal/4, xLoc+widthVal/4] - adj,...
                [prctile(cDat,25), prctile(cDat,75), prctile(cDat,75), prctile(cDat,25)],CT2(3,:)); 
                box2b.EdgeColor = 0.3.*[1 1 1]; box2b.FaceAlpha = 1.0; 
            % mean
            l = plot(ax1,[xLoc-widthVal/4, xLoc+widthVal/4] - adj,[nanmean(cDat), nanmean(cDat)],'Linewidth',1.5,'Color',CT2(end,:));
    end

% number coauthors per study
    ax2 = axes('position',[0.15 0.41 0.675 0.09]); hold on; grid off; 
        set(ax2,'Color','none','linewidth',1.0,'fontsize',10,'Box','off','xaxislocation','top','yaxislocation','right','Xcolor','none'); hold on;
        ylabel([{'Number coauthors'},{'per study'}]); 
        xlim([0+0.5 K+1-0.5]);
        ylim([0 20]); set(ax2,'Ytick',[0:5:20]); 
        % set(ax2,'Ytick',0:2:10,'yscale','log'); hold on;
        plot([0+0.5 K+1-0.5],[0 0],'linewidth',1,'Color',CT4(end-1,:).*[1 1 1],'LineStyle',':');

    % number coauthors per study
    for i = 1:size(timeBins,1)
        % men
        xLoc = i-barWidth/2; cDat = male.coauthors{i}; cDat(isnan(cDat)) = [];
            % 95 percentile range
            l = plot(ax2,[xLoc xLoc] + adj,[prctile(cDat,2.5), prctile(cDat,97.5)],'Linewidth',1,'Color',0.3.*[1 1 1]);
            % Interquartile range
            box2a = fill(ax2,[xLoc-widthVal/4, xLoc-widthVal/4, xLoc+widthVal/4, xLoc+widthVal/4] + adj,...
                [prctile(cDat,25), prctile(cDat,75), prctile(cDat,75), prctile(cDat,25)],CT4(3,:)); 
                box2a.EdgeColor = 0.3.*[1 1 1]; box2a.FaceAlpha = 1.0; 
            % mean
            l = plot(ax2,[xLoc-widthVal/4, xLoc+widthVal/4] + adj,[nanmean(cDat), nanmean(cDat)],'Linewidth',1.5,'Color',CT4(end,:));
        % women
        xLoc = i+barWidth/2; cDat = female.coauthors{i}; cDat(isnan(cDat)) = [];
            % 95 percentile range
            l = plot(ax2,[xLoc xLoc] - adj,[prctile(cDat,2.5), prctile(cDat,97.5)],'Linewidth',1,'Color',0.3.*[1 1 1]);
            % Interquartile range
            box2b = fill(ax2,[xLoc-widthVal/4, xLoc-widthVal/4, xLoc+widthVal/4, xLoc+widthVal/4] - adj,...
                [prctile(cDat,25), prctile(cDat,75), prctile(cDat,75), prctile(cDat,25)],CT4(3,:)); 
                box2b.EdgeColor = 0.3.*[1 1 1]; box2b.FaceAlpha = 1.0; 
            % mean
            l = plot(ax2,[xLoc-widthVal/4, xLoc+widthVal/4] - adj,[nanmean(cDat), nanmean(cDat)],'Linewidth',1.5,'Color',CT4(end,:));
    end
    
% legend
ax = axes('position', [0.16 0.535 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,['Man-led'],'Fontsize',10,'Fontweight','normal','color',CT1(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.16 0.515 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[{'Woman-led'}],'Fontsize',10,'Fontweight','normal','color',CT2(end-1,:),'HorizontalAlignment','left','FontAngle','normal');

% Now, plot the journal comparison

% re-assign colors
cd Figures/cbrewer/
warning('off','all')
    CT1 = cbrewer('seq','Blues' ,5); 
    CT2 = cbrewer('seq','Purples' ,5);
    gold = [0.975, 0.65, 0.125]; 
warning('on','all')
cd ../../

ax0 = axes('position',[0.15 0.60 0.675 0.20]); hold on; grid off; 
    set(ax0,'Color','none','linewidth',1.0,'fontsize',10,'Box','on'); hold on;
    set(ax0,'Xtick',[1:K],'Xticklabel',join(string(timeBins),'-'),'XTickLabelRotation',0);
    plotVals = nanmean([ [1:(K-1)]',[2:(K)]'],2);
    ylabel([{'Proportion studies'},{'woman-led'}]); 
    if size(timeBins,1) == 2
    ylim(ax0,[0.075 0.425]); 	
    elseif size(timeBins,1) == 3
    ylim(ax0,[0.05 0.40]); 	
    end
    xlim([0+0.5 K+1-0.5]);
    for i = 1:size(timeBins,1)-1
        plot([plotVals(i),plotVals(i)],[0 1],'--','linewidth',0.5,'color',CT4(end-1,:)); 
    end

    % \pm1 sigma community
    plotRange = [ax0.XLim(1), nanmean([ [1:(K-1)]',[2:(K)]'],2)', ax0.XLim(2)]'; 
    for i = 1:size(plotRange,1)-1
        b0 = fill(ax0,[plotRange(i),plotRange(i),plotRange(i+1),plotRange(i+1)], ...
            [propsA(i)-propsA_std(i),propsA(i)+propsA_std(i),propsA(i)+propsA_std(i),propsA(i)-propsA_std(i)], CT4(end-2,:),'linewidth',1); 
            b0.EdgeColor = 'none'; b0.FaceAlpha = 0.25;        
    end

    for i = 1:size(timeBins,1)
        % prestige
        I = prestige.year >= min(timeBins(i,:)) & prestige.year <= max(timeBins(i,:));
        Ic = [prestige.year >= min(timeBins(i,:)) & prestige.year <= max(timeBins(i,:))] & strcmp(prestige.genderF,'female');
        currError = nansum(strcmp(prestige.genderMC(I,:),'female')) ./ ...
                   (nansum(strcmp(prestige.genderMC(I,:),'female'),1) + nansum(strcmp(prestige.genderMC(I,:),'male'),1));
        
        xLoc = i-barWidth/2; cCol = CT1(2,:); 
        cDat = currError(:); % grA(I,:); cDat(isnan(cDat)) = []; cDat = cDat(:); 
        % violin plot
            h = figure(101); cd Figures/Violinplot/;  % procedure: run violin plot to get the plotting data:
            violins = violinplot(cDat,[0],'Width',widthVal,'Bandwidth',0.0075); % ,'Bandwidth',10);
            vertices = violins.ViolinPlot.Vertices; 
                upper = [vertices(1:(length(vertices)/2),1)-1, vertices(1:(length(vertices)/2),2)]; 
                lower = [vertices((length(vertices)/2+1):end,1)-1, vertices((length(vertices)/2+1):end,2)]; 
            close(h); cd ../../
            box1a = fill(ax0,[lower(:,1) + xLoc; upper(:,1) + xLoc] + adj, [lower(:,2); upper(:,2)],CT1(2,:)); 
                box1a.EdgeColor = 'k'; box1a.LineWidth = 0.5; box1a.FaceAlpha = box1Alpha; box1a.EdgeAlpha = box1Alpha + 0.2; 
            % 95 percentile range
            l = plot(ax0,[xLoc xLoc] + adj,[prctile(cDat,2.5), prctile(cDat,97.5)],'Linewidth',1,'Color',0.3.*[1 1 1]);
            % Interquartile range
            box2a = fill(ax0,[xLoc-widthVal/4, xLoc-widthVal/4, xLoc+widthVal/4, xLoc+widthVal/4] + adj,...
                [prctile(cDat,25), prctile(cDat,75), prctile(cDat,75), prctile(cDat,25)],CT1(3,:)); 
                box2a.EdgeColor = 0.3.*[1 1 1]; box2a.FaceAlpha = 1.0; 
            % mean
            l = plot(ax0,[xLoc-widthVal/4, xLoc+widthVal/4] + adj,[nanmean(cDat), nanmean(cDat)],'Linewidth',1.5,'Color',CT1(end,:));
        % other
        I = other.year >= min(timeBins(i,:)) & other.year <= max(timeBins(i,:));
        Ic = [other.year >= min(timeBins(i,:)) & other.year <= max(timeBins(i,:))] & strcmp(other.genderF,'female');
        currError = nansum(strcmp(other.genderMC(I,:),'female'),1) ./ ...
                   (nansum(strcmp(other.genderMC(I,:),'female'),1) + nansum(strcmp(other.genderMC(I,:),'male'),1));
        xLoc = i+barWidth/2; 
        cDat = currError(:); % grA(I,:); cDat(isnan(cDat)) = []; cDat = cDat(:); 
        % violin plot
            h = figure(101); cd Figures/Violinplot/; % procedure: run violin plot to get the plotting data:
            violins = violinplot(cDat,[0],'Width',widthVal,'Bandwidth',0.0075); % ,'Bandwidth',10);
            vertices = violins.ViolinPlot.Vertices; 
                upper = [vertices(1:(length(vertices)/2),1)-1, vertices(1:(length(vertices)/2),2)]; 
                lower = [vertices((length(vertices)/2+1):end,1)-1, vertices((length(vertices)/2+1):end,2)]; 
            close(h); cd ../../
            box1b = fill(ax0,[lower(:,1) + xLoc; upper(:,1) + xLoc] - adj, [lower(:,2); upper(:,2)],CT2(2,:)); 
                box1b.EdgeColor = 'k'; box1b.LineWidth = 0.5; box1b.FaceAlpha = box1Alpha; box1b.EdgeAlpha = box1Alpha + 0.2; 
            % 95 percentile range
            l = plot(ax0,[xLoc xLoc] - adj,[prctile(cDat,2.5), prctile(cDat,97.5)],'Linewidth',1,'Color',0.3.*[1 1 1]);
            % Interquartile range
            box2b = fill(ax0,[xLoc-widthVal/4, xLoc-widthVal/4, xLoc+widthVal/4, xLoc+widthVal/4] - adj,...
                [prctile(cDat,25), prctile(cDat,75), prctile(cDat,75), prctile(cDat,25)],CT2(3,:)); 
                box2b.EdgeColor = 0.3.*[1 1 1]; box2b.FaceAlpha = 1.0; 
            % mean
            l = plot(ax0,[xLoc-widthVal/4, xLoc+widthVal/4] - adj,[nanmean(cDat), nanmean(cDat)],'Linewidth',1.5,'Color',CT2(end,:));
    end

% legend
ax = axes('position', [0.16 0.855 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,['High Impact Factor journals'],'Fontsize',10,'Fontweight','normal','color',CT1(4,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.16 0.835 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[{'All other journals'}],'Fontsize',10,'Fontweight','normal','color',CT2(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.16 0.815 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[{'Proportion women (all authors; \pm1\sigma)'}],'Fontsize',10,'Fontweight','normal','color',CT4(end-1,:),'HorizontalAlignment','left','FontAngle','normal');

% % count the number of studies
for i =  1:size(timeBins)
    clearvars n
    I = find(years >= timeBins(i,1) & years <= timeBins(i,2));
    m = 1;
    for j = min(I):max(I)
        if ~isempty(journals{j})
        for k = 1:length(journals{j})
            if sum(~strcmp(gender{j}{k},"")) / length(gender{j}{k}) >= .50
            n(m,1) = 1;
            m = m + 1; 
            end
        end
        end
    end
    numStudies(i,1) = sum(n);
end

% number of data points
if size(timeBins,1) == 3
ax = axes('position', [0.185 0.78 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[strcat("{\itn} = ",num2str(numStudies(1)), " studies")],'Fontsize',8,'Fontweight','normal','color',CT4(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.445 0.62 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[strcat("{\itn} = ",num2str(numStudies(2)), " ")],'Fontsize',8,'Fontweight','normal','color',CT4(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.665 0.62 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[strcat("{\itn} = ",num2str(numStudies(3)), " ")],'Fontsize',8,'Fontweight','normal','color',CT4(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
elseif size(timeBins,1) == 2
ax = axes('position', [0.205 0.78 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[strcat("{\itn} = ",num2str(numStudies(1)), " studies")],'Fontsize',8,'Fontweight','normal','color',CT4(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.545 0.62 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[strcat("{\itn} = ",num2str(numStudies(2)), " studies")],'Fontsize',8,'Fontweight','normal','color',CT4(end-1,:),'HorizontalAlignment','left','FontAngle','normal');
end

% axis labels
ax = axes('position', [0.76 0.5175 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,['(b)'],'Fontsize',14,'Fontweight','bold','color',CT4(end,:),'HorizontalAlignment','left','FontAngle','normal');
ax = axes('position', [0.76 0.8175 0.02 0.02]); hold on; box off; set(gca, 'visible', 'off')
    t1 = text(0,0,[{'(a)'}],'Fontsize',14,'Fontweight','bold','color',CT4(end,:),'HorizontalAlignment','left','FontAngle','normal');

cd(homeFold)
